### ISSUE TITLE
Allow to run arbitrary commands before building SPEC

### ISSUE THREAD

**Issue by rinigus** [rinigus/tbuilder#17]
Some packages, such as droid-img...boot cannot be built with itself available in the repository. If it is possible to run some commands before, we can just remove these packages before building new version.

Proposed structure

```YAML
process:
  package_name.spec:
      - rm RPMS/{tool}/...
```

hmm, means we need also some macro expansion there. Should be possible though.
